# Generated by Django 5.2.5 on 2025-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('inquiry_type', models.CharField(choices=[('general', 'システム導入'), ('support', 'ご相談'), ('feedback', 'その他')], max_length=20, verbose_name='問い合わせ項目')),
                ('plan', models.CharField(blank=True, choices=[('basic', '未定'), ('standard', 'LINE連携'), ('premium', 'LINE連携＋システム'), ('enterprise', 'Webサイト制作＋システム'), ('custom', 'Webサイト制作＋予約システム＋システム')], max_length=20, verbose_name='プラン選択')),
                ('message', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
        ),
    ]
