# Generated by Django 5.2.5 on 2025-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='会社名・サロン名')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('contact_method', models.CharField(choices=[('email', 'メール'), ('phone', '電話')], max_length=10, verbose_name='希望連絡方法')),
                ('contact_date', models.DateField(blank=True, null=True, verbose_name='希望連絡日時')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
        ),
    ]
