# Generated by Django 5.2.5 on 2025-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(choices=[('service', '申し込み'), ('general', '料金について'), ('support', 'ご相談'), ('feedback', 'その他')], max_length=20, verbose_name='問い合わせ項目'),
        ),
    ]
