# Generated by Django 5.2.5 on 2025-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('date', models.DateField(verbose_name='予約日')),
                ('time', models.TimeField(verbose_name='予約時間')),
                ('message', models.TextField(blank=True, verbose_name='ご要望・メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
            ],
        ),
    ]
